name: deploy-cd

on:
 push:
  branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t fastapi-app:latest .

      - name: "Tag Docker Images"
        run: |
         docker tag fastapi-app:latest ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Push to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Add SSH private key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa

      - name: Add SSH known hosts #
        run: |
         ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          sudo apt-get update && sudo apt upgrade -y && sudo apt-get install docker.io -y
          docker login -u osakueomoruyi -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          sudo docker stop fastapi-app || true
          sudo docker rm fastapi-app || true
          sudo docker run -d --name fastapi-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          EOF